### ISSUE TITLE
Error: stream.push() after EOF

### ISSUE THREAD

**Issue by sunny-g** [bySabi/karma-tap-pretty-reporter#4]
I have karma configured with webpack and `autoWatch` and `disableStdout: false`; every time I make the first change to re-run the tests for the first time, the base reporter reports calls `specFailure`, leading to an attempted `push` to the `Readable` stream.

Stack trace: 

```
PhantomJS 2.1.1 (Linux 0.0.0) LOG: 'TAP version 13'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: '# TimeSlider is a React component'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: 'not ok 1 should be equal'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: '  ---'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: '    operator: equal'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: '    expected: true'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: '    actual:   false'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: '  ...'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: 'not ok 2 plan != count'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: '  ---'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: '    operator: fail'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: '    expected: 2'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: '    actual:   1'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: '  ...'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: ''
PhantomJS 2.1.1 (Linux 0.0.0) LOG: '1..2'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: '# tests 2'
PhantomJS 2.1.1 (Linux 0.0.0) LOG: '# pass  0'

Missing error handler on `socket`.
Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:157:17)
    at Readable.push (_stream_readable.js:135:10)
    at write (/home/sunnyg/gitdev/descarteslabs/widgets/node_modules/karma-tap-pretty-reporter/index.js:30:11)
    at writeSuite (/home/sunnyg/gitdev/descarteslabs/widgets/node_modules/karma-tap-pretty-reporter/index.js:37:7)
    at specFailure (/home/sunnyg/gitdev/descarteslabs/widgets/node_modules/karma-tap-pretty-reporter/index.js:76:5)
    at onSpecComplete (/home/sunnyg/gitdev/descarteslabs/widgets/node_modules/karma/lib/reporters/base.js:85:12)
    at .<anonymous> (/home/sunnyg/gitdev/descarteslabs/widgets/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at onResult (/home/sunnyg/gitdev/descarteslabs/widgets/node_modules/karma/lib/browser.js:217:13)
    at Socket.<anonymous> (/home/sunnyg/gitdev/descarteslabs/widgets/node_modules/karma/lib/events.js:13:22)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Socket.onevent (/home/sunnyg/gitdev/descarteslabs/widgets/node_modules/karma/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/home/sunnyg/gitdev/descarteslabs/widgets/node_modules/karma/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/home/sunnyg/gitdev/descarteslabs/widgets/node_modules/karma/node_modules/socket.io/lib/client.js:193:14)
16 09 2016 02:29:32.772:DEBUG [PhantomJS 2.1.1 (Linux 0.0.0)]: Disconnected during run, waiting 2000ms for reconnecting.
16 09 2016 02:29:34.774:WARN [PhantomJS 2.1.1 (Linux 0.0.0)]: Disconnected (1 times)
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  Disconnectedundefined
```

and then right after, the same error from Karma:

```
16 09 2016 02:29:34.780:ERROR [karma]: Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:157:17)
    at Readable.push (_stream_readable.js:135:10)
    at write (/home/sunnyg/gitdev/descarteslabs/widgets/node_modules/karma-tap-pretty-reporter/index.js:30:11)
    at onRunComplete (/home/sunnyg/gitdev/descarteslabs/widgets/node_modules/karma-tap-pretty-reporter/index.js:99:5)
    at .<anonymous> (/home/sunnyg/gitdev/descarteslabs/widgets/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:111:20)
    at emit (events.js:191:7)
    at Timeout._onTimeout (/home/sunnyg/gitdev/descarteslabs/widgets/node_modules/karma/lib/executor.js:51:17)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
16 09 2016 02:29:34.786:DEBUG [launcher]: Disconnecting all browsers
16 09 2016 02:29:34.819:DEBUG [launcher]: Process PhantomJS exited with code 0
16 09 2016 02:29:34.820:DEBUG [temp-dir]: Cleaning temp dir /tmp/karma-65530249
16 09 2016 02:29:34.825:DEBUG [launcher]: Finished all browsers
```

**Comment by bySabi** [comment]
Hello @sunny-g can you provide a bug repo example?

**Comment by bySabi** [comment]
@sunny-g  do you found something new? I was trying to reproduce the issue without look.

**Comment by sunny-g** [comment]
Hi @bySabi, I can't show you files but can describe how it came up. 

Node 6.4.0
Ubuntu 15.10

I have tests written in ES6 for Webpack-ed React/ES6 code with Karma and Tape, and when using either karma-tap or karma-tape as the "framework" with this reporter library, this error occurs. Thanks for your patience; I've since moved on to using just Karma and Mocha, but if you're unable to reproduce the error, I'll try to reproduce it on my end in a smaller shareable codebase.

**Comment by bySabi** [comment]
@sunny-g I had not test my self `karma-tap-pretty` on Linux and PhantomJS. Actually it pass travis CI on linux with node 4-6 and Firefox. 
A minimal repo will be really welcome.

Off the record karma-tap is working really fine with React and Enzyme. You can take a look here: https://github.com/bySabi/react-scrollaware

Don´t hesitate to ask me anything

**Comment by sunny-g** [comment]
@bySabi I'll give it another shot, thanks for the link.

**Comment by bySabi** [comment]
closed due inactivity.

Feel free to reopen is needed
